### ISSUE TITLE
Allow deriving new addresses

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-wallet#71]
Users need to be able to derive multiple addresses, for multiple groups.
This will be especially useful when interacting with dApps.

Here are the 3 scenarios we foresee for address derivation: 

- [x] Derive address in random group (by default)
- [x] Derive address in defined group
- [x] Derive one address per group (mining purposes)
~~Derive address for defined path~~

### Design

- [x] Create mockups (goal is to keep friction low, by hiding advanced features)

### Other tasks
- [x] https://github.com/alephium/alephium-wallet/issues/139
- [x] https://github.com/alephium/alephium-wallet/issues/137
- [x] https://github.com/alephium/alephium-wallet/issues/138
- [x] #147

**Comment by nop33** [comment]
As agreed in a call with @mvaivre and @tdroxler, and as it can be seen in the mockups:
- In the addresses page, the user will be able to click "Derive new address"
- This opens up a modal where the user can optionally specify the group they would like the address in
- If no group is given, an address win a random group will be generated by calling the appropriate method locally.
- This method accepts the path as an argument. We increment the last segment of the path until we have the address in the group that we want.
- To save computation time every time the user logs in into their wallet, we store an array of indexes (the last segment of the path) of the addresses that were generated by the user, and we only generate those.

**Comment by mvaivre** [comment]
Thanks @nop33 for centralising the discussion here, where it should be. @polarker An important friendly note about working habits : the mockups have been shared here 3 weeks ago and free for everyone to review. I've also pasted the link here and there (Github, Slack, PM) to make sure those are actually consulted.

Talking about the design and flows *after* implementation is *really* something we should avoid. Detailed mockups are here to avoid exactly that. Thanks in advance for your understanding!

Regarding your comment, have you checked the updated "Send" modal in the mockups? The amounts available in each address is clearly indicated in order to avoid confusion.

**Comment by polarker** [comment]
@mvaivre I think I try to spot the issues as early as possible, but it's not always possible. At least, it's never possible for backend design. We have to investigate (where we brainstorm), prototype implementation (where we might spot more issues), and go for final design. Even after the final design, we would still refactor the code if it's needed.

I only had the feedback until I saw @nop33's video. Sorry that I could not come up with such feedbacks when seeing the mockups, but apparently video provides more information than mockup.

I guess **we should always commit to truth not to consistency**. Let's have a call to discuss the design now that we have more ideas. Of course, if my feedback makes sense, we could refactor the design at a later stage.

**Comment by nop33** [comment]
I believe we can close this issue since the features have been implemented! We are in the testing phase before releasing. Any futher bug fixes can be reported individually and added in the `v1.2.0` milestone.
